CREATE TABLE [dbo].[Fa]
(
	[FAId] INT IDENTITY NOT NULL PRIMARY KEY,
	CONSTRAINT [FK_FA_ToBenevole] FOREIGN KEY ([FAId]) REFERENCES [Benevole] ([BenevoleId]),
	CONSTRAINT [FK_FA_ToAnimal] FOREIGN KEY ([FAId]) REFERENCES [Animal] ([AnimalId])
)
